name: Init

on:
  push:
    branches:
      - master
  pull_request:

env:
  MOCK_APP_NAME: Yu-Gi-Oh Test
jobs:
  install:
    if: github.event_name == 'push'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install package
        run: npm install

  test:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Reinstall
        run: npm install

      - name: Run tests
        run: npm test
  
  deploy:
    needs: test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Reinstall windows
        if: runner.os == 'Windows'
        run: npm install | echo "y"

      - name: Reinstall linux
        if: runner.os == 'Linux'
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Gh Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist